name: Christopher Adams
title: christopheradams.io
description: >-
  Photography, AI, Blockchain, Hypermedia
email: info@christopheradams.io
image: /assets/images/20220522-1235_Taipei_TaipeiDangdai_L1000274-0.jpg
location: Taipei
newsletter: https://news.cxadams.com/subscription/form
timezone: ETC/UTC

url: https://christopheradams.io
baseurl: ""

source_url: "https://github.com/christopheradams/christopheradams.io/blob/master/"

social_links:
  - title: Twitter
    url: https://twitter.com/christopheradam
  - title: Nostr
    url: https://nostr.at/cxadams.com
  - title: Bluesky
    url: https://bsky.app/profile/cxadams.com
  - title: Instagram
    url: https://www.instagram.com/christopherleeadams
  - title: Mastodon
    url: https://mastodon.social/@christopheradams
  - title: GitHub
    url: https://github.com/christopheradams
  - title: PGP
    url: https://keys.openpgp.org/search?q=chris%40raysend.com
  - title: Newsletter
    url: https://news.cxadams.com/subscription/form

# Authors
# see _data/authors.yml
author:
  name: Christopher Adams
  email: info@christopheradams.io
  uri: https://christopheradams.io

# Collections
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:year/:month/:day/:title/
      author: christopheradams

paginate: 12
paginate_path: "/page/:num/"

feed:
  posts_limit: 25

excerpt_separator: <!--more-->

sass:
  sass_dir: _scss
  style: compressed
  quiet_deps: true

jekyll-archives:
  enabled:
    - year
    - categories
    - tags
  layouts:
    tag: tag
  permalinks:
    year: '/archives/:year/'
    category: '/categories/:name/'
    tag: '/tags/:name/'

picture:
  relative_url: false
  suppress_warnings: true

plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll_picture_tag
exclude:
  - CNAME
  - LICENSE
  - README.md
  - Makefile
  - package-lock.json
  - package.json
  - screenshot.png
  - vendor
